import type { APIRoute, GetStaticPaths } from 'astro';
import { getCollection } from 'astro:content';

// Serves each docs page's raw markdown at `<page-path>.md` so agents can
// fetch a single page without downloading llms-full.txt. Pages generated by
// starlight-openapi are not in the collection; /openapi.json covers the API.
export const getStaticPaths = (async () => {
  const entries = await getCollection('docs');
  return entries.map((entry) => ({
    params: { slug: entry.id || 'index' },
    props: { body: entry.body ?? '' },
  }));
}) satisfies GetStaticPaths;

export const GET: APIRoute = ({ props }) =>
  new Response(props.body, {
    headers: { 'Content-Type': 'text/markdown; charset=utf-8' },
  });
