{{- if and (not .Values.existingSecret) .Values.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remotecache.fullname" . }}-admin
  labels:
    {{- include "remotecache.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.adminToken | quote }}
{{- end }}
{{- if and (eq .Values.storage.strategy "s3") (not .Values.s3.existingSecret) .Values.s3.accessKeyId }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remotecache.fullname" . }}-s3
  labels:
    {{- include "remotecache.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.s3.accessKeyId | quote }}
  secret-access-key: {{ .Values.s3.secretAccessKey | quote }}
  {{- if .Values.s3.sessionToken }}
  session-token: {{ .Values.s3.sessionToken | quote }}
  {{- end }}
{{- end }}
