import { defineRouteMiddleware } from '@astrojs/starlight/route-data';
import { getCollection } from 'astro:content';

const docsIds = new Set((await getCollection('docs')).map((entry) => entry.id || 'index'));

export const onRequest = defineRouteMiddleware((context) => {
  const { head, id } = context.locals.starlightRoute;
  const routeId = id || 'index';
  // API reference pages are generated by starlight-openapi and have no
  // per-page image; they fall back to the site-wide card.
  const imagePath = docsIds.has(routeId) ? `/og/${routeId}.png` : '/og.png';
  const imageUrl = new URL(imagePath, context.site);
  head.push(
    { tag: 'meta', attrs: { property: 'og:image', content: imageUrl.href } },
    { tag: 'meta', attrs: { name: 'twitter:image', content: imageUrl.href } },
  );
});
